Repository TrNgTien/Spotify_Clone, pull requests merged in 2021-05, with the labels that each got.

#2 Finish APIs for Authentication & Authorization
  README.md
  client/package-lock.json
  client/package.json
  client/src/components/PlayList.js
  client/src/components/UploadForm.js
  client/src/constants/BE_CONNECTION.js
  client/src/index.js
  client/src/pages/MainPage.js
  client/src/pages/MusicPlace/DashBoard.js
  client/src/pages/MusicPlace/MainControl.js
  client/src/pages/MusicPlace/MusicBar.js
  client/src/pages/MusicPlace/MusicGrid.js
  client/src/pages/MusicPlace/styles/DashBoard.css
  client/src/pages/MusicPlace/styles/MainControl.css
  client/src/pages/MusicPlace/styles/MusicBar.css
  client/src/pages/MusicPlace/styles/MusicGrid.css
  client/src/pages/MusicPlace/styles/compressed/MainControl.min.css
  client/src/pages/MusicPlace/styles/compressed/MusicBar.min.css
  client/src/pages/auth/LoginForm.js
  client/src/pages/auth/RegisterForm.js
  client/src/pages/styles/MusicGrid.css
  client/src/routes/MainRoute.js
  client/src/slices/CounterSlice.js
  client/src/store.js
  server/controller/Songs/songHandler.js
  server/controller/Users/UserQueries.js
  server/controller/Users/userHandler.js
  server/database/db_connection.js
  server/index.js
  server/package-lock.json
  server/package.json
  server/routes/songsRoutes.js
  server/routes/usersRoutes.js
Labels: Back-end Works, Front-end Works

#7 Finish getUser + auto generate userTypeID
  server/controller/Songs/attribute.js
  server/controller/Songs/songHandler.js
  server/controller/Users/UserQueries.js
  server/controller/Users/userAttribute.js
  server/controller/Users/userHandler.js
  server/routes/usersRoutes.js
Labels: Back-end Works

#6 Modal for Functionality post songs
  client/src/assets/background.jpg
  client/src/components/HeaderBar.js
  client/src/components/HomePage.js
  client/src/components/UploadForm.js
  client/src/components/styles/HomePage.css
  client/src/pages/MusicPlace/DashBoard.js
  client/src/pages/MusicPlace/MainControl.js
  client/src/pages/MusicPlace/MusicBar.js
  client/src/pages/MusicPlace/MusicGrid.js
  client/src/pages/auth/LoginForm.js
  client/src/slices/CounterSlice.js
  client/src/slices/FormModal.js
  client/src/store.js
Labels: Front-end Works

#12 UI/filter
  client/package-lock.json
  client/src/pages/MusicPlace/FilterPage.js
  client/src/pages/MusicPlace/MainControl.js
  client/src/pages/MusicPlace/MusicGrid.js
  client/src/pages/MusicPlace/styles/FilterPage.css
  client/src/routes/MainRoute.js
Labels: Front-end Works

#13 Refactor Code for userAPI & Finish playlist APIs
  server/controller/Playlists/playlistAttribute.js
  server/controller/Playlists/playlistHandler.js
  server/controller/Users/UserQueries.js
  server/controller/Users/userHandler.js
  server/index.js
  server/routes/playlistRoutes.js
  server/routes/usersRoutes.js
Labels: Back-end Works

#16 Render all songs in Home Page
  client/src/api/Song.js
  client/src/components/HomePage.js
  client/src/constants/Song.js
  client/src/pages/MusicPlace/DashBoard.js
Labels: Front-end Works

#17 Handle functionality for filtering songs
  client/src/api/Artist.js
  client/src/api/Genre.js
  client/src/components/Select/FilterSelect.js
  client/src/components/SongFilter.js
  client/src/components/styles/SongFilter.css
  client/src/constants/Artist.js
  client/src/constants/DropDown.js
  client/src/constants/Genre.js
  client/src/pages/MusicPlace/FilterPage.js
  client/src/pages/MusicPlace/MusicGrid.js
Labels: Front-end Works
